services:
  - type: web
    name: remix-recipes
    env: node
    buildCommand: npm install && npm run build:render
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: remix-recipes-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: AUTH_COOKIE_SECRET
        generateValue: true
    healthCheckPath: /health

databases:
  - name: remix-recipes-db
    databaseName: remix_recipes
    user: remix_user