// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/discover": {
    params: {};
  };
  "/discover/:recipeId": {
    params: {
      "recipeId": string;
    };
  };
  "/login": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/validate-magic-link": {
    params: {};
  };
  "/recipe-image": {
    params: {};
  };
  "/cookies": {
    params: {};
  };
  "/theme.css": {
    params: {};
  };
  "/app/recipes": {
    params: {};
  };
  "/app/recipes/new": {
    params: {};
  };
  "/app/recipes/:recipeId": {
    params: {
      "recipeId": string;
    };
  };
  "/app/recipes/:recipeId/edit": {
    params: {
      "recipeId": string;
    };
  };
  "/app/grocery-list": {
    params: {};
  };
  "/app/pantry": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/my-recipes": {
    params: {};
  };
  "/add-recipe": {
    params: {};
  };
  "/grocery-list": {
    params: {};
  };
  "/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/discover" | "/discover/:recipeId" | "/login" | "/logout" | "/validate-magic-link" | "/recipe-image" | "/cookies" | "/theme.css" | "/app/recipes" | "/app/recipes/new" | "/app/recipes/:recipeId" | "/app/recipes/:recipeId/edit" | "/app/grocery-list" | "/app/pantry" | "/settings" | "/my-recipes" | "/add-recipe" | "/grocery-list" | "/home";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/discover.tsx": {
    id: "routes/discover";
    page: "/discover";
  };
  "routes/discover.$recipeId.tsx": {
    id: "routes/discover.$recipeId";
    page: "/discover/:recipeId";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/validate-magic-link.tsx": {
    id: "routes/validate-magic-link";
    page: "/validate-magic-link";
  };
  "routes/recipe-image.tsx": {
    id: "routes/recipe-image";
    page: "/recipe-image";
  };
  "routes/cookies.ts": {
    id: "routes/cookies";
    page: "/cookies";
  };
  "routes/theme[.]css.tsx": {
    id: "routes/theme[.]css";
    page: "/theme.css";
  };
  "routes/app/recipes.tsx": {
    id: "routes/app/recipes";
    page: "/app/recipes";
  };
  "routes/app/recipes/new.tsx": {
    id: "routes/app/recipes/new";
    page: "/app/recipes/new";
  };
  "routes/app/recipes/$recipeId.simple.tsx": {
    id: "routes/app/recipes/$recipeId.simple";
    page: "/app/recipes/:recipeId";
  };
  "routes/app/recipes/$recipeId.edit-simple.tsx": {
    id: "routes/app/recipes/$recipeId.edit-simple";
    page: "/app/recipes/:recipeId/edit";
  };
  "routes/app/grocery-list.tsx": {
    id: "routes/app/grocery-list";
    page: "/app/grocery-list";
  };
  "routes/app/pantry.tsx": {
    id: "routes/app/pantry";
    page: "/app/pantry";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/my-recipes.tsx": {
    id: "routes/my-recipes";
    page: "/my-recipes";
  };
  "routes/add-recipe.tsx": {
    id: "routes/add-recipe";
    page: "/add-recipe";
  };
  "routes/grocery-list.tsx": {
    id: "routes/grocery-list";
    page: "/grocery-list";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
};